The dimension of y_tensor is torch.Size([10201, 2]).
The dimension of y_expanded is torch.Size([500, 10201, 2]) after expanding.
The zero coordinate of y_expanded is temporal and the first coordinate is space.
The dimensions of the initial conditions are: (500, 101)
The dimensions of the solutions are: (500, 101, 101)
The dimension of u_tensor is torch.Size([500, 101]).
The dimension of u_expanded is torch.Size([500, 10201, 101]) after expanding.
The loaded solution dataset has dimension (500, 101, 101),
	 while the arranged linearized dataset has dimension (500, 10201).
The dimension of s_tensor is torch.Size([500, 10201]).
The dimension of s_expanded is torch.Size([500, 10201, 1]) after expanding.
The training dataset has 4080400 samples, while the train_loader has 511 batches.
The training dataset has 1020100 samples, while the train_loader has 511 batches.
cuda
Epoch 1
Epoch 1, Loss: 0.00809393470871, Improvement: 0.00809393470871, Best Loss: inf in Epoch 1, Time: 49.66 seconds
Epoch 2
Epoch 2, Loss: 0.00161751164005, Improvement: -0.00647642306866, Best Loss: inf in Epoch 1, Time: 47.24 seconds
Epoch 3
Epoch 3, Loss: 0.00125074517775, Improvement: -0.00036676646230, Best Loss: inf in Epoch 1, Time: 47.26 seconds
Epoch 4
Epoch 4, Loss: 0.00104707530542, Improvement: -0.00020366987232, Best Loss: inf in Epoch 1, Time: 47.26 seconds
Epoch 5
Epoch 5, Loss: 0.00089381653939, Improvement: -0.00015325876604, Best Loss: inf in Epoch 1, Time: 47.22 seconds
Epoch 6
Epoch 6, Loss: 0.00077605901064, Improvement: -0.00011775752875, Best Loss: inf in Epoch 1, Time: 47.28 seconds
Epoch 7
Epoch 7, Loss: 0.00067962300378, Improvement: -0.00009643600685, Best Loss: inf in Epoch 1, Time: 47.32 seconds
Epoch 8
Epoch 8, Loss: 0.00060826958496, Improvement: -0.00007135341882, Best Loss: inf in Epoch 1, Time: 47.23 seconds
Epoch 9
Epoch 9, Loss: 0.00058978438697, Improvement: -0.00001848519799, Best Loss: inf in Epoch 1, Time: 47.24 seconds
Epoch 10
Epoch 10, Loss: 0.00057349763168, Improvement: -0.00001628675529, Best Loss: inf in Epoch 1, Time: 47.32 seconds
ERROR:fipy:Uncaught exception:
Traceback (most recent call last):
  File "/qfs/people/weiz828/DON/1d_train/1dd.py", line 341, in <module>
    model.load_state_dict(torch.load(model_params_best, map_location=torch.device(device), weights_only=True))
                                     ^^^^^^^^^^^^^^^^^
NameError: name 'model_params_best' is not defined. Did you mean: 'model_params_final'?
